FROM amazonlinux:2

ARG LAMBDASHARP_VERSION
ENV DOTNET_NOLOGO=1
ENV PATH="/opt/tools:${PATH}"

RUN rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm

RUN yum update -y && \
    yum install -y wget

RUN wget https://packages.microsoft.com/keys/microsoft.asc && \
    rpm --import ./microsoft.asc

RUN yum install -y \
    openssl-devel \
    libnghttp2-devel \
    libidn-devel \
    libunwind \
    krb5 \
    libuuid \
    lttng-ust \
    zlib \
    gcc \
    dotnet-sdk-3.1

# Making a new directory to use because this https://github.com/moby/moby/issues/3639
RUN mkdir /opt/tools/
RUN if [ -z "${LAMBDASHARP_VERSION}" ] ; then \
dotnet tool install LambdaSharp.Tool --tool-path /opt/tools/ \
; else \
dotnet tool install LambdaSharp.Tool --tool-path /opt/tools/ --version ${LAMBDASHARP_VERSION} \
; fi \
; lash

WORKDIR /project