FROM microsoft/dotnet:2.1-sdk
WORKDIR /project

ENV LAMBDASHARP=/tools/LambdaSharpTool

##########
# utils
##########
RUN apt-get update &&\
    apt-get install zip -y

###############
# lambdasharp
###############
COPY ./lash-command.sh /usr/bin/lash
RUN mkdir /tools && \
    cd /tools && \
    git clone https://github.com/LambdaSharp/LambdaSharpTool.git && \
    chmod +x /usr/bin/lash && \
    lash
