FROM microsoft/dotnet:2.1-sdk
WORKDIR /project

ENV LAMBDASHARP=/tools/LambdaSharpTool

#################
# update sources
#################
RUN echo "deb http://ftp.de.debian.org/debian testing main" >> /etc/apt/sources.list

####################
# utils & python
####################
RUN apt-get update && \
    apt-get install zip python3 python3-distutils -y

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 50

######
# pip
######
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py

##########
# aws cli
##########
RUN pip install awscli

###############
# lambdasharp
###############
COPY ./lash-command.sh /usr/bin/lash
RUN mkdir /tools && \
    cd /tools && \
    git clone https://github.com/smyleeface/LambdaSharpTool.git -b jukeboxalexa-custom-v0.3 && \
    chmod +x /usr/bin/lash && \
    lash
