FROM amazonlinux:2018.03
WORKDIR /project

ARG LAMBDASHARP_VERSION=master
ENV LAMBDASHARP=/opt/LambdaSharpTool

ENV DOTNET_FILENAME=dotnet-sdk-2.2.104-linux-x64.tar.gz
ENV DOTNET_URL=https://download.visualstudio.microsoft.com/download/pr/69937b49-a877-4ced-81e6-286620b390ab/8ab938cf6f5e83b2221630354160ef21/$DOTNET_FILENAME

ENV PATH="/usr/bin:${PATH}"

##########
# utils
##########
RUN yum install wget git zip unzip -y

###############
# Dotnet
###############
RUN wget $DOTNET_URL
RUN mkdir -p /usr/share/dotnet && \
    tar zxf $DOTNET_FILENAME -C /usr/share/dotnet && \
    ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet && \
    dotnet --version && \
    rm $DOTNET_FILENAME

###############
# lambdasharp
###############
RUN echo "dotnet run -p ${LAMBDASHARP}/src/LambdaSharp.Tool/LambdaSharp.Tool.csproj -- $@" >> /usr/bin/lash
RUN cd /opt && \
    git clone --single-branch --branch $LAMBDASHARP_VERSION https://github.com/LambdaSharp/LambdaSharpTool.git && \
    chmod +x /usr/bin/lash && \
    lash
