FROM amazonlinux:2

ARG LAMBDASHARP_VERSION
ENV DOTNET_NOLOGO=1
ENV PATH="/opt/tools:${PATH}"

RUN rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm

RUN yum update -y && \
    yum install -y wget tar gzip make

RUN wget https://packages.microsoft.com/keys/microsoft.asc && \
    rpm --import ./microsoft.asc

RUN yum install -y \
    openssl-devel \
    libnghttp2-devel \
    libidn-devel \
    libunwind \
    krb5 \
    libuuid \
    lttng-ust \
    zlib \
    gcc \
    dotnet-sdk-3.1

##########
# python
##########
RUN wget https://www.python.org/ftp/python/3.6.10/Python-3.6.10.tgz
RUN gunzip Python-3.6.10.tgz
RUN tar xf Python-3.6.10.tar
RUN rm -f Python-3.6.0.tar
RUN cd Python-3.6.10 && \
	./configure && \
	make && \
	make altinstall

RUN yum clean all && rm -rf /var/cache/yum

RUN ln -sf /usr/local/bin/python3.6 /usr/bin/python && \
	python --version

################
# lambdasharp
################
RUN mkdir /opt/tools
RUN if [ -z "${LAMBDASHARP_VERSION}" ] ; then \
dotnet tool install LambdaSharp.Tool --tool-path /opt/tools/ \
; else \
dotnet tool install LambdaSharp.Tool --tool-path /opt/tools/ --version ${LAMBDASHARP_VERSION} \
; fi \
; lash

WORKDIR /project