FROM mcr.microsoft.com/dotnet/core/sdk:2.2
WORKDIR /project

ARG LAMBDASHARP_VERSION=master
ENV LAMBDASHARP=/opt/LambdaSharpTool

ENV PATH="/usr/bin:${PATH}"

#################
# update sources
#################
RUN echo "deb http://ftp.de.debian.org/debian testing main" >> /etc/apt/sources.list

####################
# utils & python
####################
RUN apt-get update && \
    apt-get install zip python3 python3-distutils -y

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 50

######
# pip
######
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py

##########
# aws cli
##########
RUN pip install awscli

###############
# lambdasharp
###############
RUN echo "dotnet run -p ${LAMBDASHARP}/src/LambdaSharp.Tool/LambdaSharp.Tool.csproj -- $@" >> /usr/bin/lash
RUN cd /opt && \
    git clone --single-branch --branch $LAMBDASHARP_VERSION https://github.com/LambdaSharp/LambdaSharpTool.git && \
    chmod +x /usr/bin/lash && \
    lash

